-- =============================================================================
-- Categories Migration: Global → Per-User
-- =============================================================================
-- Run this entire script in Supabase SQL Editor in one go.
-- It's wrapped in a transaction so either everything succeeds or nothing changes.
--
-- dim_categories        → stays as-is (template/defaults table)
-- dim_categories_users  → new per-user table
-- =============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Create new per-user categories table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dim_categories_users (
    categories_id_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name    TEXT           NOT NULL,
    type             category_type  NOT NULL,
    spending_type    spending_type,
    is_active        BOOLEAN        DEFAULT true,
    user_id_fk       UUID           NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at       TIMESTAMPTZ    DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Copy existing categories into new table for your user
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO dim_categories_users
    (category_name, type, spending_type, is_active, user_id_fk)
SELECT
    category_name, type, spending_type, is_active,
    '<user_id_removed_for_privacy>'
FROM dim_categories;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Enable RLS on the new per-user table
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE dim_categories_users ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE POLICY "Users can read own categories"
    ON dim_categories_users FOR SELECT
    USING (user_id_fk = auth.uid());

CREATE OR REPLACE POLICY "Users can insert own categories"
    ON dim_categories_users FOR INSERT
    WITH CHECK (user_id_fk = auth.uid());

CREATE OR REPLACE POLICY "Users can update own categories"
    ON dim_categories_users FOR UPDATE
    USING (user_id_fk = auth.uid());

CREATE OR REPLACE POLICY "Users can delete own categories"
    ON dim_categories_users FOR DELETE
    USING (user_id_fk = auth.uid());

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Trigger: seed defaults from dim_categories on every new signup
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.seed_default_categories()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.dim_categories_users
        (category_name, type, spending_type, is_active, user_id_fk)
    SELECT
        category_name, type, spending_type, is_active, NEW.id
    FROM public.dim_categories;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.seed_default_categories();

COMMIT;