

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."category_type" AS ENUM (
    'income',
    'expense',
    'saving',
    'transfer',
    'investment',
    'exclude'
);


ALTER TYPE "public"."category_type" OWNER TO "postgres";


CREATE TYPE "public"."spending_type" AS ENUM (
    'Core',
    'Fun',
    'Future',
    'Income',
    'Necessary'
);


ALTER TYPE "public"."spending_type" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."seed_default_categories"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    INSERT INTO public.dim_categories_users
        (category_name, type, spending_type, is_active, user_id_fk)
    SELECT
        category_name, type, spending_type, is_active, NEW.id
    FROM public.dim_categories;

    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."seed_default_categories"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."dim_categories" (
    "categories_id_pk" bigint NOT NULL,
    "category_name" "text" NOT NULL,
    "type" "public"."category_type" NOT NULL,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "spending_type" "public"."spending_type" DEFAULT 'Fun'::"public"."spending_type" NOT NULL
);


ALTER TABLE "public"."dim_categories" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."categories_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."categories_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."categories_id_seq" OWNED BY "public"."dim_categories"."categories_id_pk";



ALTER TABLE "public"."dim_categories" ALTER COLUMN "categories_id_pk" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categories_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dim_accounts" (
    "accounts_id_pk" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id_fk" "uuid" NOT NULL,
    "account_name" "text" NOT NULL,
    "type" "text" NOT NULL,
    "currency" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "account_is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."dim_accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dim_categories_users" (
    "categories_id_pk" bigint NOT NULL,
    "category_name" "text" NOT NULL,
    "type" "public"."category_type" NOT NULL,
    "spending_type" "public"."spending_type",
    "is_active" boolean DEFAULT true,
    "user_id_fk" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."dim_categories_users" OWNER TO "postgres";


ALTER TABLE "public"."dim_categories_users" ALTER COLUMN "categories_id_pk" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dim_categories_users_categories_id_pk_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dim_exchange_rates" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "base_currency" "text" NOT NULL,
    "target_currency" "text" NOT NULL,
    "rate" numeric NOT NULL,
    "fetched_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."dim_exchange_rates" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dim_recurring" (
    "recurring_id_pk" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id_fk" "uuid" NOT NULL,
    "account_id_fk" "uuid" NOT NULL,
    "category_id_fk" bigint NOT NULL,
    "savings_fund_id_fk" "uuid",
    "amount" numeric NOT NULL,
    "cadence" "text" NOT NULL,
    "next_date" "date" NOT NULL,
    "notes" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "dim_recurring_cadence_check" CHECK (("cadence" = ANY (ARRAY['weekly'::"text", 'biweekly'::"text", 'monthly'::"text", 'quarterly'::"text", 'yearly'::"text"])))
);


ALTER TABLE "public"."dim_recurring" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."dim_savings_funds" (
    "savings_funds_id_pk" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id_fk" "uuid" NOT NULL,
    "fund_name" "text" NOT NULL,
    "target_amount" bigint DEFAULT '0'::bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "fund_is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."dim_savings_funds" OWNER TO "postgres";


COMMENT ON COLUMN "public"."dim_savings_funds"."fund_is_active" IS 'Funds that users might want to delete but are linked in fct_transactions get disabled rather than deleted';



CREATE TABLE IF NOT EXISTS "public"."fct_budgets" (
    "id_pk" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id_fk" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "month" smallint DEFAULT '1'::smallint NOT NULL,
    "year" smallint DEFAULT '1'::smallint NOT NULL,
    "plan_json" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."fct_budgets" OWNER TO "postgres";


COMMENT ON TABLE "public"."fct_budgets" IS 'Keeping a monthly budget - simple, mimic Excel and add features';



CREATE TABLE IF NOT EXISTS "public"."fct_dividend_portfolios" (
    "id_pk" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id_fk" "uuid" NOT NULL,
    "portfolio_value" numeric(18,2) DEFAULT 0 NOT NULL,
    "portfolio_json" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."fct_dividend_portfolios" OWNER TO "postgres";


COMMENT ON TABLE "public"."fct_dividend_portfolios" IS 'Stores each authenticated user''s dividend portfolio (one row per user). portfolio_json is an array of stock rows: ticker, weight_pct, dividend_yield, yield_frequency.';



COMMENT ON COLUMN "public"."fct_dividend_portfolios"."portfolio_value" IS 'Total portfolio value used to compute estimated income amounts.';



COMMENT ON COLUMN "public"."fct_dividend_portfolios"."portfolio_json" IS 'JSONB array: [{"ticker": "AAPL", "weight_pct": 25.0, "dividend_yield": 0.55, "yield_frequency": "annual"}, ...]';



CREATE TABLE IF NOT EXISTS "public"."fct_transactions" (
    "id_pk" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id_fk" "uuid" NOT NULL,
    "account_id_fk" "uuid" NOT NULL,
    "category_id_fk" bigint NOT NULL,
    "amount" numeric NOT NULL,
    "date" "date" NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "savings_fund_id_fk" "uuid"
);


ALTER TABLE "public"."fct_transactions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."test" (
    "id" integer NOT NULL,
    "type" "text",
    "amount" double precision
);


ALTER TABLE "public"."test" OWNER TO "postgres";


ALTER TABLE ONLY "public"."dim_accounts"
    ADD CONSTRAINT "accounts_id_key" UNIQUE ("accounts_id_pk");



ALTER TABLE ONLY "public"."dim_accounts"
    ADD CONSTRAINT "accounts_pkey" PRIMARY KEY ("accounts_id_pk");



ALTER TABLE ONLY "public"."dim_categories"
    ADD CONSTRAINT "categories_id_key" UNIQUE ("categories_id_pk");



ALTER TABLE ONLY "public"."dim_categories"
    ADD CONSTRAINT "categories_name_key" UNIQUE ("category_name");



ALTER TABLE ONLY "public"."dim_categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("categories_id_pk");



ALTER TABLE ONLY "public"."dim_categories_users"
    ADD CONSTRAINT "dim_categories_users_pkey" PRIMARY KEY ("categories_id_pk");



ALTER TABLE ONLY "public"."dim_exchange_rates"
    ADD CONSTRAINT "dim_exchange_rates_base_currency_target_currency_key" UNIQUE ("base_currency", "target_currency");



ALTER TABLE ONLY "public"."dim_exchange_rates"
    ADD CONSTRAINT "dim_exchange_rates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dim_recurring"
    ADD CONSTRAINT "dim_recurring_pkey" PRIMARY KEY ("recurring_id_pk");



ALTER TABLE ONLY "public"."fct_budgets"
    ADD CONSTRAINT "fct_budgets_pkey" PRIMARY KEY ("id_pk");



ALTER TABLE ONLY "public"."fct_dividend_portfolios"
    ADD CONSTRAINT "fct_dividend_portfolios_pkey" PRIMARY KEY ("id_pk");



ALTER TABLE ONLY "public"."fct_dividend_portfolios"
    ADD CONSTRAINT "fct_dividend_portfolios_user_unique" UNIQUE ("user_id_fk");



ALTER TABLE ONLY "public"."dim_savings_funds"
    ADD CONSTRAINT "savings_funds_pkey" PRIMARY KEY ("savings_funds_id_pk");



ALTER TABLE ONLY "public"."test"
    ADD CONSTRAINT "test_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fct_transactions"
    ADD CONSTRAINT "transactions_id_key" UNIQUE ("id_pk");



ALTER TABLE ONLY "public"."fct_transactions"
    ADD CONSTRAINT "transactions_pkey1" PRIMARY KEY ("id_pk");



CREATE INDEX "dim_cat_user_type_idx" ON "public"."dim_categories_users" USING "btree" ("user_id_fk", "type");



CREATE INDEX "fct_transactions_amount_idx" ON "public"."fct_transactions" USING "btree" ("amount");



CREATE INDEX "fct_transactions_notes_date_idx" ON "public"."fct_transactions" USING "btree" ("notes", "date");



CREATE INDEX "fct_tx_notes_trgm_idx" ON "public"."fct_transactions" USING "gin" ("notes" "public"."gin_trgm_ops");



CREATE INDEX "fct_tx_user_account_date_idx" ON "public"."fct_transactions" USING "btree" ("user_id_fk", "account_id_fk", "date" DESC);



CREATE INDEX "fct_tx_user_category_date_idx" ON "public"."fct_transactions" USING "btree" ("user_id_fk", "category_id_fk", "date" DESC);



CREATE INDEX "fct_tx_user_date_id_idx" ON "public"."fct_transactions" USING "btree" ("user_id_fk", "date" DESC, "id_pk" DESC);



CREATE INDEX "fct_tx_user_fund_date_idx" ON "public"."fct_transactions" USING "btree" ("user_id_fk", "savings_fund_id_fk", "date" DESC);



CREATE INDEX "idx_dividend_portfolios_user_id" ON "public"."fct_dividend_portfolios" USING "btree" ("user_id_fk");



CREATE INDEX "idx_exchange_rates_pair" ON "public"."dim_exchange_rates" USING "btree" ("base_currency", "target_currency");



CREATE INDEX "ix_recurring_user_active" ON "public"."dim_recurring" USING "btree" ("user_id_fk", "is_active");



CREATE INDEX "ix_recurring_user_nextdate" ON "public"."dim_recurring" USING "btree" ("user_id_fk", "next_date");



ALTER TABLE ONLY "public"."dim_accounts"
    ADD CONSTRAINT "dim_accounts_user_id_fk_fkey" FOREIGN KEY ("user_id_fk") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dim_categories_users"
    ADD CONSTRAINT "dim_categories_users_user_id_fk_fkey" FOREIGN KEY ("user_id_fk") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dim_recurring"
    ADD CONSTRAINT "dim_recurring_account_id_fk_fkey" FOREIGN KEY ("account_id_fk") REFERENCES "public"."dim_accounts"("accounts_id_pk") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."dim_recurring"
    ADD CONSTRAINT "dim_recurring_category_id_fk_fkey" FOREIGN KEY ("category_id_fk") REFERENCES "public"."dim_categories_users"("categories_id_pk") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."dim_recurring"
    ADD CONSTRAINT "dim_recurring_savings_fund_id_fk_fkey" FOREIGN KEY ("savings_fund_id_fk") REFERENCES "public"."dim_savings_funds"("savings_funds_id_pk") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."dim_recurring"
    ADD CONSTRAINT "dim_recurring_user_id_fk_fkey" FOREIGN KEY ("user_id_fk") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dim_savings_funds"
    ADD CONSTRAINT "dim_savings_funds_user_id_fk_fkey" FOREIGN KEY ("user_id_fk") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."fct_budgets"
    ADD CONSTRAINT "fct_budgets_user_id_fk_fkey" FOREIGN KEY ("user_id_fk") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."fct_dividend_portfolios"
    ADD CONSTRAINT "fct_dividend_portfolios_user_id_fk_fkey" FOREIGN KEY ("user_id_fk") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."fct_transactions"
    ADD CONSTRAINT "fct_transactions_account_id_fk_fkey" FOREIGN KEY ("account_id_fk") REFERENCES "public"."dim_accounts"("accounts_id_pk") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."fct_transactions"
    ADD CONSTRAINT "fct_transactions_category_id_fk_fkey" FOREIGN KEY ("category_id_fk") REFERENCES "public"."dim_categories_users"("categories_id_pk") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."fct_transactions"
    ADD CONSTRAINT "fct_transactions_savings_fund_id_fk_fkey" FOREIGN KEY ("savings_fund_id_fk") REFERENCES "public"."dim_savings_funds"("savings_funds_id_pk") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."fct_transactions"
    ADD CONSTRAINT "fct_transactions_user_id_fk_fkey" FOREIGN KEY ("user_id_fk") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Delete own accounts" ON "public"."dim_accounts" FOR DELETE USING (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Delete own transactions" ON "public"."fct_transactions" FOR DELETE USING (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Enable delete access for users based on user_id_fk" ON "public"."fct_budgets" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id_fk"));



CREATE POLICY "Enable insert access for users based on user_id_fk" ON "public"."fct_budgets" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id_fk"));



CREATE POLICY "Enable select access for users based on user_id_fk" ON "public"."fct_budgets" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id_fk"));



CREATE POLICY "Enable update access for users based on user_id_fk" ON "public"."fct_budgets" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id_fk")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id_fk"));



CREATE POLICY "Insert own accounts" ON "public"."dim_accounts" FOR INSERT WITH CHECK (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Insert own transactions" ON "public"."fct_transactions" FOR INSERT WITH CHECK (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Read own accounts" ON "public"."dim_accounts" FOR SELECT USING (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Read own transactions" ON "public"."fct_transactions" FOR SELECT USING (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Update own accounts" ON "public"."dim_accounts" FOR UPDATE USING (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid"))) WITH CHECK (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Update own transactions" ON "public"."fct_transactions" FOR UPDATE USING (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid"))) WITH CHECK (("user_id_fk" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can delete own categories" ON "public"."dim_categories_users" FOR DELETE USING (("user_id_fk" = "auth"."uid"()));



CREATE POLICY "Users can delete own dividend portfolio" ON "public"."fct_dividend_portfolios" FOR DELETE USING (("auth"."uid"() = "user_id_fk"));



CREATE POLICY "Users can insert own categories" ON "public"."dim_categories_users" FOR INSERT WITH CHECK (("user_id_fk" = "auth"."uid"()));



CREATE POLICY "Users can insert own dividend portfolio" ON "public"."fct_dividend_portfolios" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id_fk"));



CREATE POLICY "Users can manage their own savings funds" ON "public"."dim_savings_funds" USING (("auth"."uid"() = "user_id_fk")) WITH CHECK (("auth"."uid"() = "user_id_fk"));



CREATE POLICY "Users can read own categories" ON "public"."dim_categories_users" FOR SELECT USING (("user_id_fk" = "auth"."uid"()));



CREATE POLICY "Users can update own categories" ON "public"."dim_categories_users" FOR UPDATE USING (("user_id_fk" = "auth"."uid"()));



CREATE POLICY "Users can update own dividend portfolio" ON "public"."fct_dividend_portfolios" FOR UPDATE USING (("auth"."uid"() = "user_id_fk")) WITH CHECK (("auth"."uid"() = "user_id_fk"));



CREATE POLICY "Users can view own dividend portfolio" ON "public"."fct_dividend_portfolios" FOR SELECT USING (("auth"."uid"() = "user_id_fk"));



ALTER TABLE "public"."dim_accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dim_categories_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dim_exchange_rates" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dim_recurring" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dim_savings_funds" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "exchange_rates_read" ON "public"."dim_exchange_rates" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."fct_budgets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fct_dividend_portfolios" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fct_transactions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "funds_insert" ON "public"."dim_savings_funds" FOR INSERT TO "authenticated" WITH CHECK (("user_id_fk" = "auth"."uid"()));



CREATE POLICY "recurring_delete" ON "public"."dim_recurring" FOR DELETE TO "authenticated" USING (("user_id_fk" = "auth"."uid"()));



CREATE POLICY "recurring_insert" ON "public"."dim_recurring" FOR INSERT TO "authenticated" WITH CHECK (("user_id_fk" = "auth"."uid"()));



CREATE POLICY "recurring_select" ON "public"."dim_recurring" FOR SELECT TO "authenticated" USING (("user_id_fk" = "auth"."uid"()));



CREATE POLICY "recurring_update" ON "public"."dim_recurring" FOR UPDATE TO "authenticated" USING (("user_id_fk" = "auth"."uid"()));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_in"("cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_in"("cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_in"("cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_in"("cstring") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_out"("public"."gtrgm") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_out"("public"."gtrgm") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_out"("public"."gtrgm") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_out"("public"."gtrgm") TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."gin_extract_query_trgm"("text", "internal", smallint, "internal", "internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gin_extract_query_trgm"("text", "internal", smallint, "internal", "internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gin_extract_query_trgm"("text", "internal", smallint, "internal", "internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gin_extract_query_trgm"("text", "internal", smallint, "internal", "internal", "internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gin_extract_value_trgm"("text", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gin_extract_value_trgm"("text", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gin_extract_value_trgm"("text", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gin_extract_value_trgm"("text", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gin_trgm_consistent"("internal", smallint, "text", integer, "internal", "internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gin_trgm_consistent"("internal", smallint, "text", integer, "internal", "internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gin_trgm_consistent"("internal", smallint, "text", integer, "internal", "internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gin_trgm_consistent"("internal", smallint, "text", integer, "internal", "internal", "internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gin_trgm_triconsistent"("internal", smallint, "text", integer, "internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gin_trgm_triconsistent"("internal", smallint, "text", integer, "internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gin_trgm_triconsistent"("internal", smallint, "text", integer, "internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gin_trgm_triconsistent"("internal", smallint, "text", integer, "internal", "internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_compress"("internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_compress"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_compress"("internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_consistent"("internal", "text", smallint, "oid", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_consistent"("internal", "text", smallint, "oid", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_consistent"("internal", "text", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_consistent"("internal", "text", smallint, "oid", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_decompress"("internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_decompress"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_decompress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_decompress"("internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_distance"("internal", "text", smallint, "oid", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_distance"("internal", "text", smallint, "oid", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_distance"("internal", "text", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_distance"("internal", "text", smallint, "oid", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_options"("internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_options"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_options"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_options"("internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_penalty"("internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_penalty"("internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_penalty"("internal", "internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_picksplit"("internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_picksplit"("internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_picksplit"("internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_same"("public"."gtrgm", "public"."gtrgm", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_same"("public"."gtrgm", "public"."gtrgm", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_same"("public"."gtrgm", "public"."gtrgm", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_same"("public"."gtrgm", "public"."gtrgm", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_union"("internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_union"("internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_union"("internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."seed_default_categories"() TO "anon";
GRANT ALL ON FUNCTION "public"."seed_default_categories"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."seed_default_categories"() TO "service_role";



GRANT ALL ON FUNCTION "public"."set_limit"(real) TO "postgres";
GRANT ALL ON FUNCTION "public"."set_limit"(real) TO "anon";
GRANT ALL ON FUNCTION "public"."set_limit"(real) TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_limit"(real) TO "service_role";



GRANT ALL ON FUNCTION "public"."show_limit"() TO "postgres";
GRANT ALL ON FUNCTION "public"."show_limit"() TO "anon";
GRANT ALL ON FUNCTION "public"."show_limit"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."show_limit"() TO "service_role";



GRANT ALL ON FUNCTION "public"."show_trgm"("text") TO "postgres";
GRANT ALL ON FUNCTION "public"."show_trgm"("text") TO "anon";
GRANT ALL ON FUNCTION "public"."show_trgm"("text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."show_trgm"("text") TO "service_role";



GRANT ALL ON FUNCTION "public"."similarity"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."similarity"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."similarity"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."similarity"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."similarity_dist"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."similarity_dist"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."similarity_dist"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."similarity_dist"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."similarity_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."similarity_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."similarity_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."similarity_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity_commutator_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_commutator_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_commutator_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_commutator_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_commutator_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_commutator_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_commutator_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_commutator_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity_commutator_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity_commutator_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity_commutator_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity_commutator_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity_dist_commutator_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_commutator_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_commutator_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_commutator_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity_dist_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity_op"("text", "text") TO "service_role";


















GRANT ALL ON TABLE "public"."dim_categories" TO "anon";
GRANT ALL ON TABLE "public"."dim_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."dim_categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."dim_accounts" TO "anon";
GRANT ALL ON TABLE "public"."dim_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."dim_accounts" TO "service_role";



GRANT ALL ON TABLE "public"."dim_categories_users" TO "anon";
GRANT ALL ON TABLE "public"."dim_categories_users" TO "authenticated";
GRANT ALL ON TABLE "public"."dim_categories_users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dim_categories_users_categories_id_pk_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dim_categories_users_categories_id_pk_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dim_categories_users_categories_id_pk_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dim_exchange_rates" TO "anon";
GRANT ALL ON TABLE "public"."dim_exchange_rates" TO "authenticated";
GRANT ALL ON TABLE "public"."dim_exchange_rates" TO "service_role";



GRANT ALL ON TABLE "public"."dim_recurring" TO "anon";
GRANT ALL ON TABLE "public"."dim_recurring" TO "authenticated";
GRANT ALL ON TABLE "public"."dim_recurring" TO "service_role";



GRANT ALL ON TABLE "public"."dim_savings_funds" TO "anon";
GRANT ALL ON TABLE "public"."dim_savings_funds" TO "authenticated";
GRANT ALL ON TABLE "public"."dim_savings_funds" TO "service_role";



GRANT ALL ON TABLE "public"."fct_budgets" TO "anon";
GRANT ALL ON TABLE "public"."fct_budgets" TO "authenticated";
GRANT ALL ON TABLE "public"."fct_budgets" TO "service_role";



GRANT ALL ON TABLE "public"."fct_dividend_portfolios" TO "anon";
GRANT ALL ON TABLE "public"."fct_dividend_portfolios" TO "authenticated";
GRANT ALL ON TABLE "public"."fct_dividend_portfolios" TO "service_role";



GRANT ALL ON TABLE "public"."fct_transactions" TO "anon";
GRANT ALL ON TABLE "public"."fct_transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."fct_transactions" TO "service_role";



GRANT ALL ON TABLE "public"."test" TO "anon";
GRANT ALL ON TABLE "public"."test" TO "authenticated";
GRANT ALL ON TABLE "public"."test" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























