-- Per-user feature flags: dim_features (global registry) + dim_features_users (per-user state).
--
-- Mirrors the dim_categories -> dim_categories_users pattern: a global template table plus a
-- per-user table seeded on signup by a trigger on auth.users.
--
-- Flags are granted, not self-served: dim_features_users has a SELECT policy only. Writes come
-- from the security-definer seed trigger below (owner bypasses RLS) and from the SQL editor.


-- ================================================================================================
--                                   dim_features (global registry)
-- ================================================================================================

CREATE TABLE "public"."dim_features" (
    "features_id_pk"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "feature_key"         text NOT NULL UNIQUE,
    "feature_name"        text NOT NULL,
    "feature_description" text,
    "is_active"           boolean NOT NULL DEFAULT true,
    "created_at"          timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "public"."dim_features" ENABLE ROW LEVEL SECURITY;

-- Read-only for every authenticated user; no write policies, so writes are migration-only.
-- Same shape as dim_exchange_rates.
CREATE POLICY "Select features" ON "public"."dim_features"
    FOR SELECT TO "authenticated" USING (true);


-- ================================================================================================
--                                dim_features_users (per-user state)
-- ================================================================================================

CREATE TABLE "public"."dim_features_users" (
    "features_users_id_pk" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id_fk"           uuid NOT NULL DEFAULT auth.uid()
                               REFERENCES auth.users(id) ON DELETE CASCADE,
    "feature_key"          text NOT NULL
                               REFERENCES public.dim_features(feature_key) ON DELETE CASCADE,
    "is_enabled"           boolean NOT NULL DEFAULT false,
    "created_at"           timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at"           timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "dim_features_users_unique" UNIQUE ("user_id_fk", "feature_key")
);

CREATE INDEX "dim_features_users_user_id_idx" ON "public"."dim_features_users" ("user_id_fk");

ALTER TABLE "public"."dim_features_users" ENABLE ROW LEVEL SECURITY;

-- SELECT only: a user must not be able to turn on their own features.
CREATE POLICY "Select own features" ON "public"."dim_features_users"
    FOR SELECT USING (("user_id_fk" = auth.uid()));


-- ================================================================================================
--                                   Register the first feature
-- ================================================================================================

INSERT INTO public.dim_features (feature_key, feature_name, feature_description)
VALUES ('screenshot_import', 'Screenshot import',
        'Import draft transactions from a screenshot of bank notifications')
ON CONFLICT (feature_key) DO NOTHING;


-- ================================================================================================
--                                   Seed trigger on signup
-- ================================================================================================

CREATE OR REPLACE FUNCTION "public"."seed_user_features"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET search_path = public, pg_temp
    AS $$
BEGIN
    INSERT INTO public.dim_features_users (user_id_fk, feature_key, is_enabled)
    SELECT NEW.id, f.feature_key, false
    FROM public.dim_features f
    WHERE f.is_active
    ON CONFLICT (user_id_fk, feature_key) DO NOTHING;

    RETURN NEW;
EXCEPTION WHEN OTHERS THEN
    -- Never block a signup over a feature flag. A missing row already reads as `false`.
    RAISE WARNING 'seed_user_features failed for user %: %', NEW.id, SQLERRM;
    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."seed_user_features"() OWNER TO "postgres";

CREATE TRIGGER "on_auth_user_created_seed_features"
    AFTER INSERT ON "auth"."users"
    FOR EACH ROW EXECUTE FUNCTION "public"."seed_user_features"();


-- ================================================================================================
--                                   Backfill existing users
-- ================================================================================================

INSERT INTO public.dim_features_users (user_id_fk, feature_key, is_enabled)
SELECT u.id, f.feature_key, false
FROM auth.users u
CROSS JOIN public.dim_features f
WHERE f.is_active
ON CONFLICT (user_id_fk, feature_key) DO NOTHING;


-- ================================================================================================
-- Adding a feature later takes two statements in a new migration:
--
--   INSERT INTO public.dim_features (feature_key, feature_name, feature_description)
--   VALUES ('<key>', '<Name>', '<what it does>');
--
--   INSERT INTO public.dim_features_users (user_id_fk, feature_key, is_enabled)
--   SELECT u.id, '<key>', false FROM auth.users u
--   ON CONFLICT (user_id_fk, feature_key) DO NOTHING;
--
-- The read path defaults a missing row to `false`, so forgetting the second statement degrades to
-- "feature off", never to an error.
--
-- Turning a flag on for a user (SQL editor -- data edits there are fine, the never-hand-edit rule
-- is about schema):
--
--   UPDATE public.dim_features_users
--   SET is_enabled = true, updated_at = now()
--   WHERE feature_key = '<key>'
--     AND user_id_fk = (SELECT id FROM auth.users WHERE email = '<you@example.com>');
-- ================================================================================================
