-- Transaction tags: dim_tags (user-scoped) + fct_transaction_tags (M2M junction)

CREATE TABLE "public"."dim_tags" (
    "tags_id_pk" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id_fk" uuid NOT NULL DEFAULT auth.uid(),
    "tag_name" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    CONSTRAINT "dim_tags_user_tag_unique" UNIQUE ("user_id_fk", "tag_name")
);

ALTER TABLE "public"."dim_tags" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Select own tags" ON "public"."dim_tags"
    FOR SELECT USING (("user_id_fk" = auth.uid()));

CREATE POLICY "Insert own tags" ON "public"."dim_tags"
    FOR INSERT WITH CHECK (("user_id_fk" = auth.uid()));

CREATE POLICY "Update own tags" ON "public"."dim_tags"
    FOR UPDATE USING (("user_id_fk" = auth.uid())) WITH CHECK (("user_id_fk" = auth.uid()));

CREATE POLICY "Delete own tags" ON "public"."dim_tags"
    FOR DELETE USING (("user_id_fk" = auth.uid()));


CREATE TABLE "public"."fct_transaction_tags" (
    "transaction_id_fk" uuid NOT NULL REFERENCES "public"."fct_transactions"("id_pk") ON DELETE CASCADE,
    "tag_id_fk" bigint NOT NULL REFERENCES "public"."dim_tags"("tags_id_pk") ON DELETE CASCADE,
    "user_id_fk" uuid NOT NULL DEFAULT auth.uid(),
    PRIMARY KEY ("transaction_id_fk", "tag_id_fk")
);

CREATE INDEX "fct_transaction_tags_tag_id_idx" ON "public"."fct_transaction_tags" ("tag_id_fk");

ALTER TABLE "public"."fct_transaction_tags" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Select own transaction tags" ON "public"."fct_transaction_tags"
    FOR SELECT USING (("user_id_fk" = auth.uid()));

CREATE POLICY "Insert own transaction tags" ON "public"."fct_transaction_tags"
    FOR INSERT WITH CHECK (("user_id_fk" = auth.uid()));

CREATE POLICY "Delete own transaction tags" ON "public"."fct_transaction_tags"
    FOR DELETE USING (("user_id_fk" = auth.uid()));
